removed .unique()
Since cudf v0.7 Series does not support unique() on string datatype: "AttributeError: 'StringColumn' object has no attribute 'unique'
"